version: '3.8'

# Services
services:

    # PHP Service
    php_8:
        container_name: php_8
        build:
            dockerfile: php-dockerfile
        volumes:
            - './php-files-app2:/var/www/html/app2'
            - './php-files-app3:/var/www/html/app3'

        depends_on:
            - mariadb

    # PHP Service
    php_7:
        container_name: php_7
        image: php:7.2-fpm
        volumes:
            - './php-files-app1:/var/www/html/app1'
        depends_on:
            - mariadb

    # App 1 Nginx Service
    App1:
        container_name: nginx-app1
        image: nginx:latest
        ports:
            - 8080:80
        links:
            - 'php_7'
        volumes:
            - './php-files-app1:/var/www/html/app1'
            - './nginx-conf-app1:/etc/nginx/conf.d'
        depends_on:
            - php_7


    # App 2 Nginx Service
    App2:
        container_name: nginx-app2
        image: nginx:latest
        ports:
            - 8081:80
        links:
            - 'php_8'
        volumes:
            - './php-files-app2:/var/www/html/app2'
            - './nginx-conf-app2:/etc/nginx/conf.d'
        depends_on:
            - php_8

    # App 1 Nginx Service
    App3:
        container_name: nginx-app3
        image: nginx:latest
        ports:
            - 8083:80
        links:
            - 'php_8'
        volumes:
            - './php-files-app3:/var/www/html/app3'
            - './nginx-conf-app3:/etc/nginx/conf.d'
        depends_on:
            - php_8

    # MariaDB Service
    mariadb:
        image: mariadb:10.9
        environment:
            MYSQL_ROOT_PASSWORD: Telekomunikas1
        volumes:
            - mysqldata:/var/lib/mysql

    # phpMyAdmin Service
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - 8090:80
        environment:
            PMA_HOST: mariadb
        depends_on:
            - mariadb

# Volumes
volumes:
  mysqldata: