version: '3.8'

# Services
services:

    # PHP Service
    php-56:
        container_name: php-56
        build:
            dockerfile: php56-dockerfile
        volumes:
            - './www-jurnal-pypip/public:/var/www/html/jurnal-pypip'
            - './www-jurnal-files:/home/jurnal/files'
            - ./config/php56.ini:/usr/local/etc/php/php.ini
        depends_on:
            - mariadb

    # PHP Service
    php-72:
        container_name: php-72
        build:
            dockerfile: php72-dockerfile
        volumes:
            - './www-pypip/public:/var/www/html/pypip'
            - ./config/php72.ini:/usr/local/etc/php/php.ini
        depends_on:
            - mariadb

    # PHP Service
    php-74:
        container_name: php-74
        build:
            dockerfile: php74-dockerfile
        volumes:
            - './www-akses-pypip/public:/var/www/html/akses-pypip'
            - ./config/php74.ini:/usr/local/etc/php/php.ini
        depends_on:
            - mariadb

    # PHP Service
    php-80:
        container_name: php-80
        build:
            dockerfile: php80-dockerfile
        volumes:
            - './www-cas-pypip/public:/var/www/html/cas-pypip'
            - ./config/php80.ini:/usr/local/etc/php/php.ini
        depends_on:
            - mariadb

    # App 1 Nginx Service
    app-pypip:
        container_name: app-pypip
        image: nginx:latest
        ports:
            - 8080:80
        links:
            - 'php-72'
        volumes:
            - './www-pypip/public:/var/www/html/pypip'
            - './nginx-conf-pypip:/etc/nginx/conf.d'
            - './log/error-pypip.log:/var/log/nginx/error.log'
            - './log/access-pypip.log:/var/log/nginx/access.log'
        depends_on:
            - php-72

    # App 1 Nginx Service
    app-akses-pypip:
        container_name: app-akses-pypip
        image: nginx:latest
        ports:
            - 8081:80
        links:
            - 'php-74'
        volumes:
            - './www-akses-pypip/public:/var/www/html/akses-pypip'
            - './nginx-conf-akses-pypip:/etc/nginx/conf.d'
            - './log/error-akses-pypip.log:/var/log/nginx/error.log'
            - './log/access-akses-pypip.log:/var/log/nginx/access.log'
        depends_on:
            - php-74

    # App 1 Nginx Service
    app-cas-pypip:
        container_name: app-cas-pypip
        image: nginx:latest
        ports:
            - 8082:80
        links:
            - 'php-80'
        volumes:
            - './www-cas-pypip/public:/var/www/html/cas-pypip'
            - './nginx-conf-cas-pypip:/etc/nginx/conf.d'
            - './log/error-cas-pypip.log:/var/log/nginx/error.log'
            - './log/access-cas-pypip.log:/var/log/nginx/access.log'
        depends_on:
            - php-80

    # App 1 Nginx Service
    app-jurnal-pypip:
        container_name: app-jurnal-pypip
        image: nginx:latest
        ports:
            - 8083:80
        links:
            - 'php-56'
        volumes:
            - './www-jurnal-pypip/public:/var/www/html/jurnal-pypip'
            - './nginx-conf-jurnal-pypip:/etc/nginx/conf.d'
            - './log/error-jurnal-pypip.log:/var/log/nginx/error.log'
            - './log/access-jurnal-pypip.log:/var/log/nginx/access.log'
            - './www-jurnal-files:/home/jurnal/files'
        depends_on:
            - php-56


    # MariaDB Service
    mariadb:
        container_name: mariadb
        image: mariadb:10.9
        environment:
            MYSQL_ROOT_PASSWORD: PASSWORDnya
        volumes:
            - ./mysqldata:/var/lib/mysql

    # phpMyAdmin Service
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - 8090:80
        environment:
            PMA_HOST: mariadb
        depends_on:
            - mariadb
